### PR TITLE
Track controller iteration 2

### PR DESCRIPTION
**Pull request by chrisg564**
- Basic module UI and testing UI
- Added very crude implementation of some core features
- Still needs a lot of cleanup and to improve overall class structures

### CODE REVIEW

**Comment by chrisg564** [comment]
@ctrlaltf2 I have many linting errors and I'm sure most others do too. Should linting be made optional for iteration 2 code? 

Nvm I don't think they are required.

**Comment by ctrlaltf2** [comment]
yeah for time's sake, skip, but we should fix stuff asap once iteration 2 is over

**Review by cag185 — APPROVED** [review]
Looks good, will develop branch need to have all modules as active tho? I see that you commented them out for developing your branch but eventually we all need to have them as active

**Comment by ctrlaltf2** [comment]
it'd be a flex to show the modules running together, and we could test it on one laptop really easily

**Review by cwh35 — APPROVED** [review]

**Review by ctrlaltf2 — APPROVED** [review]

**Comment by cag185** [comment]
> it'd be a flex to show the modules running together, and we could test it on one laptop really easily

Is this not what we would have to do? Otherwise you would have to relaunch electron after every module is done being displayed.

**Comment by ctrlaltf2** [comment]
> > it'd be a flex to show the modules running together, and we could test it on one laptop really easily
> 
> Is this not what we would have to do? Otherwise you would have to relaunch electron after every module is done being displayed.

oops mistyped, I'm tired my bad. I meant for presentation, we could either all swap laptops when we show modules, or merge everything into develop making sure they at least run together without dying, presenting off one laptop

**Comment by chrisg564** [comment]
@ctrlaltf2 @cag185 I changed main.js back so all modules render by default. We should talk as a group before class about how we want to present though.

**Comment by ctrlaltf2** [comment]
sending it

**Pull request merged**
